routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::group(['namespace'=>'User'], function(){
  Route::get('/', 'HomeController@index')->name('index');
  Route::get('/news/{slug}', 'NewsController@index')->name('news-detail');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
  Route::post('/visitor', 'DashboardController@create')->name('visitors');
});

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::resource('/news', 'NewsController', ['names'=>'news']);
        Route::put('/account/update', 'ProfileController@update')->name('account.update');
        Route::post('/account/password', 'ProfileController@password')->name('account.password');
        Route::resource('/setting', 'MetaController', ['names'=>'setting']);
    });
});
Auth::routes();

app/Meta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Meta extends Model
{
  public function uploadImage($image, $name) {
      $des    = 'upload/images/';
      $image->move($des, $name);
  }

  public function getImage() {
      $path   = 'upload/images/';
      return url($path.$this->logo);
  }
}

app/Http/Controllers/Admin/MetaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Meta;
use Illuminate\Support\Str;
use Validator;
use Carbon\Carbon;
use Illuminate\Http\Request;

class MetaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     protected function validationData($request){
         $this->validator      = Validator::make(
             $request,
             [
                 'title'          => 'required',
                 'keyword'            => 'required',
                 'description'            => 'required',
             ],
             [
                 'required'          => ':attribute is required.'
             ],
             [
                 'title'          => 'Site Title',
                 'keyword'            => 'Keyword',
                 'description'            => 'Description',
             ]
         );
     }

    public function index()
    {
      $models = Meta::first();
      return view('admin.meta.index', compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Meta  $visitor
     * @return \Illuminate\Http\Response
     */
    public function show(Meta $visitor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Meta  $visitor
     * @return \Illuminate\Http\Response
     */
    public function edit(Meta $visitor)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Meta  $visitor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validationData($request->all());
      if ($this->validator->fails()) {
          return redirect()->back()->withInput($request->all())->withErrors($this->validator->errors());
      }

      $model = Meta::findOrFail($id);
      $model->title = $request->title;
      $model->keyword = $request->keyword;
      $model->description = $request->description;
      if($request->file('logo') != null){
        $name = $request->logo->getClientOriginalName();

        $model->uploadImage($request->file('logo'), $name);
        $model->logo = $name;
      }

      $model->save();

      return redirect()->route('admin.setting.index')->with('info', 'Success update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Meta  $visitor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Meta $visitor)
    {
        //
    }
}

resources/views/admin/meta/index.blade.php
@extends('layouts.admin')
@section('title')
Setting
@endsection
@section('content')
<div class="card shadow mb-4">
  <div class="card-body">
    <form class="row" action="{{route('admin.setting.update',$models->id)}}" method="POST" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="col-lg-6">
        <div class="form-group">
          <label class="text-muted" for="site_title">Site Title</label>
          <input type="text" class="form-control" id="site_title" name="title" required placeholder="Site Title" value="{{$models->title}}">
        </div>
        <div class="form-group">
          <label class="text-muted" for="keyword">Site Keyword</label>
          <input type="text" class="form-control" id="keyword" name="keyword" required placeholder="Bali, Travel, Denpasar, Bali Travel News, News" value="{{$models->keyword}}">
        </div>
        <div class="form-group">
          <label class="text-muted" for="description">Description</label>
          <textarea class="form-control" id="description" name="description" required placeholder="Site Description" rows="8" cols="80">{{$models->description}}</textarea>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">
          <label class="text-muted" for="logo">Logo</label>
          <div class="input-group">
            <div class="custom-file">
              <input type="file" name="logo" class="custom-file-input" id="logo">
              <label class="custom-file-label" for="logo">Choose file</label>
            </div>
          </div>
          @if($models->logo != "")
            <img style="width: 150px;border-radius: 5px;margin-top:10px;background: #ddd;padding: 10px;" src="{{$models->getImage()}}" alt="{{$models->site_title}}">
          @endif
        </div>
      </div>
      <div class="col-md-12 mt-3">
        <div class="form-group">
           <button type="submit" class="btn btn-success">Save Change</button>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection
@section('script')

@endsection