routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::group(['namespace'=>'User'], function(){
  Route::get('/', 'HomeController@index')->name('index');
  Route::get('/news/{slug}', 'NewsController@index')->name('news-detail');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
  Route::post('/visitor', 'DashboardController@create')->name('visitors');
});

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
        Route::resource('/news', 'NewsController', ['names'=>'news']);
        Route::put('/account/update', 'ProfileController@update')->name('account.update');
        Route::post('/account/password', 'ProfileController@password')->name('account.password');
        Route::resource('/setting', 'MetaController', ['names'=>'setting']);
    });
});
Auth::routes();

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
  public function uploadImage($image, $name) {
      $des    = 'upload/images/';
      $image->move($des, $name);
  }

  public function getImage() {
      $path   = 'upload/images/';
      return url($path.$this->img);
  }

  public function date()
  {
      return date('d M Y H:i', strtotime($this->created_at));
  }

  public function content()
  {
      $des = stripslashes(strip_tags($this->content));
      return substr($des, 0, 100);
  }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\News;
use Illuminate\Support\Str;
use Validator;
use Carbon\Carbon;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     protected function validationData($request){
         $this->validator      = Validator::make(
             $request,
             [
                 'title'          => 'required',
                 'content'            => 'required',
                 'status'            => 'required',
             ],
             [
                 'required'          => ':attribute is required.'
             ],
             [
                 'title'           => 'News Title',
                 'content'             => 'News Content',
                 'status'             => 'Status',
             ]
         );
     }

    public function index(Request $request)
    {
        $name = $request->get('name');

        if ($name) {
            $models = News::where('title', 'like', '%' . $name . '%');
        } else {
            $models = News::orderBy('created_at', 'desc');
        }

        $models = $models->paginate(20);
        return view('admin.news.index',compact('models'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(Request $request)
     {
         $this->validationData($request->all());
         if ($this->validator->fails()) {
             return redirect()->back()->withInput($request->all())->withErrors($this->validator->errors());
         }

         $model = new News();
         $model->title = $request->title;
         $model->slug = Str::slug($model->title, '-');
         $model->content = $request->content;
         $model->status = $request->status;
         if($request->file('img') != null){
           $name = $request->img->getClientOriginalName();

           $model->uploadImage($request->file('img'), $name);
           $model->img = $name;
         }
         $model->save();

         return redirect()->route('admin.news.index')->with('info', 'Success add data');
     }
    /**
     * Display the specified resource.
     *
     * @param  \App\News  $News
     * @return \Illuminate\Http\Response
     */
    public function show()
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\News  $News
     * @return \Illuminate\Http\Response
     */
    public function edit(News $News)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\News  $News
     * @return \Illuminate\Http\Response
     */
     public function update(Request $request, $id)
     {
         $this->validationData($request->all());
         if ($this->validator->fails()) {
             return redirect()->back()->withInput($request->all())->withErrors($this->validator->errors());
         }

         $model = News::findOrFail($id);
         $model->title = $request->title;
         $model->slug = Str::slug($model->title, '-');
         $model->content = $request->content;
         $model->status = $request->status;
         if($request->file('img') != null){
           $name = $request->img->getClientOriginalName();

           $model->uploadImage($request->file('img'), $name);
           $model->img = $name;
         }

         $model->save();

         return redirect()->route('admin.news.index')->with('info', 'Success update data');
     }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\News  $News
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $model = News::findOrFail($id);
      $model->delete();

      return redirect()->route('admin.news.index')->with('info', 'Success delete data');
    }
}

app/Http/Controllers/Api/NewsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\News;

class NewsController extends Controller
{

    public function post()
    {

        $data = array();
        $post = News::where('status', 1)->get();
        foreach($post as $item){
            $data_item = array();
            $data_item['id'] = $item->id;
            $data_item['img'] = $item->getImage();
            $data_item['title'] = $item->title;
            $data_item['slug'] = $item->slug;
            $data_item['created_at'] = $item->date();
            $data_item['content'] = $item->content();
            $data[] = $data_item;
        }

        return $data;
    }

}

app/Http/Controllers/User/NewsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($slug)
    {
        $models = News::where('slug', $slug)->first();
        $recents = News::where('slug', '!=', $slug)->get();
        return view('user.news.detail', compact('models', 'recents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\News  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {
        //
    }
}

resources/views/admin/news/create.blade.php
<div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{{route('admin.news.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="modal-body">
          <div class="form-group">
            <label for="" class="label">Title</label>
            <input type="text" class="form-control" autocomplete="off" name="title">
          </div>
          <div class="form-group">
            <label for="" class="label">Featured Image</label>
            <div class="input-group mb-3">
              <div class="custom-file">
                <input type="file" name="img" class="custom-file-input" id="inputGroupFile01">
                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="label">Content</label>
            <textarea class="form-control my-editor" name="content" rows="8" cols="80" autocomplete="off"></textarea>
            <input type="hidden" name="status" value="1">
          </div>
          <div class="form-group">
             <label for="" class="label">Status</label>
             <select name="status" class="form-control">
               <option value="0">Draft</option>
               <option value="1">Active</option>
             </select>
          </div>
        </div>
        <div class="modal-footer">
          <button type="reset" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </form>
    </div>
  </div>
</div>
@section('script')
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
  tinymce.init({
    selector: 'textarea.my-editor',
    height: 500,
    menubar: false,
    plugins: [
      'advlist autolink lists link image charmap print preview anchor',
      'searchreplace visualblocks code fullscreen',
      'insertdatetime media table paste code help wordcount'
    ],
    toolbar: 'undo redo | formatselect | ' +
    'bold italic backcolor | alignleft aligncenter ' +
    'alignright alignjustify | bullist numlist outdent indent | ' +
    'removeformat | help',
    content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
  });
</script>
@endsection

resources/views/admin/news/index.blade.php
@extends('layouts.admin')
@section('title')
News
@endsection
@section('content')
<a href="javascript:void(0)" class="btn btn-primary btn-icon-split shadow" data-toggle="modal" data-target="#create">
  <span class="icon text-white-50">
    <i class="fas fa-plus"></i>
  </span>
  <span class="text">Add Data</span>
</a>
@include('admin.news.create')
<div class="card shadow mt-4 mb-4">
   <!-- Card Body -->
   <div class="card-body">
      <div class="table-responsive">
         <table class="table table-bordered table-stripped">
            <thead>
               <tr>
                  <td>
                     No
                  </td>
                  <td>
                     Title
                  </td>
                  <td>
                     Status
                  </td>
                  <td>
                     Created at
                  </td>
                  <td>
                     Action
                  </td>
               </tr>
            </thead>
            <tbody>
               @if($models->count() == 0)
               <tr>
                  <td colspan="6" align="center">
                     No data
                  </td>
               </tr>
               @endif
               @foreach($models as $key => $item)
               <tr>
                  <td>
                     {{ ($models->perPage() * ($models->currentPage() - 1)) + ($key + 1) }}
                  </td>
                  <td>
                     {{$item->title}}
                  </td>
                  <td>
                    @if($item->status == 1)
                     <span class="badge badge-success">Published</span>
                    @else
                     <span class="badge badge-secondary">Draft</span>
                    @endif
                  </td>
                  <td>
                     {{Carbon\Carbon::parse($item->created_at)->format('d-m-Y H:i:s')}}
                  </td>
                  <td>
                     <form action="{{route('admin.news.destroy',$item->id)}}" method="POST" onsubmit="return confirm('Are you sure?')">
                        @method('DELETE')
                        @csrf
                        <a href="javascript:void(0)" class="btn btn-warning btn-circle btn-sm" data-toggle="modal" data-target="#edit-{{$item->id}}">
                        <i class="fas fa-pen"></i>
                        </a>
                        <button class="btn btn-danger btn-circle btn-sm">
                        <i class="fas fa-trash"></i>
                        </button>
                     </form>
                     <div class="modal fade" id="edit-{{$item->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                       <div class="modal-dialog modal-lg" role="document">
                         <div class="modal-content">
                           <div class="modal-header">
                             <h5 class="modal-title" id="exampleModalLabel">Add Data</h5>
                             <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                               <span aria-hidden="true">&times;</span>
                             </button>
                           </div>
                           <form action="{{route('admin.news.update', $item->id)}}" method="POST" enctype="multipart/form-data">
                             @csrf
                             @method('PUT')
                             <div class="modal-body">
                               <div class="form-group">
                                 <label for="" class="label">Title</label>
                                 <input type="text" value="{{$item->title}}" class="form-control" autocomplete="off" name="title">
                               </div>
                               <div class="form-group">
                                 <label for="" class="label">Featured Image</label>
                                 <div class="input-group">
                                   <div class="custom-file">
                                     <input type="file" name="img" class="custom-file-input">
                                     <label class="custom-file-label" for="logo">Choose file</label>
                                   </div>
                                 </div>
                                 @if($item->img != "")
                                   <img style="width:30%; margin-top:10px;" src="{{$item->getImage()}}" alt="{{$item->title}}">
                                 @endif
                               </div>
                               <div class="form-group">
                                 <label for="" class="label">Content</label>
                                 <textarea class="form-control my-editor" name="content" rows="8" cols="80" autocomplete="off">{!! $item->content !!}</textarea>
                                 <input type="hidden" name="status" value="1">
                               </div>
                               <div class="form-group">
                                  <label for="" class="label">Status</label>
                                  <select name="status" class="form-control">
                                  <option value="1"  @if($item->status == '1') selected @endif>Active</option>
                                  <option value="0"  @if($item->status == '0') selected @endif>Draft</option>
                                  </select>
                               </div>
                             </div>
                             <div class="modal-footer">
                               <button type="reset" class="btn btn-secondary" data-dismiss="modal">Close</button>
                               <button type="submit" class="btn btn-primary">Save changes</button>
                             </div>
                           </form>
                         </div>
                       </div>
                     </div>
                  </td>
               </tr>
               @endforeach
            </tbody>
         </table>
      </div>
      {{ $models->appends(\Request::query())->links() }}
   </div>
</div>
@endsection
@section('script')
@endsection